In [1]:
import numpy as np

a = np.random.randn(5)

In [2]:
print(a)

[ 0.89562222  0.94966366 -1.11431814  1.44873562  0.68237336]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[ 0.89562222  0.94966366 -1.11431814  1.44873562  0.68237336]


In [5]:
print(np.dot(a, a.T))

5.51017343433529


In [6]:
a = np.random.randn(5, 1)
print(a)

[[ 0.73226316]
 [ 0.77316765]
 [ 0.61584182]
 [-0.71718867]
 [-0.63159872]]


In [7]:
print(a.T)

[[ 0.73226316  0.77316765  0.61584182 -0.71718867 -0.63159872]]


In [8]:
print(np.dot(a, a.T))

[[ 0.53620933  0.56616218  0.45095827 -0.52517084 -0.46249647]
 [ 0.56616218  0.59778821  0.47614897 -0.55450708 -0.4883317 ]
 [ 0.45095827  0.47614897  0.37926115 -0.44167477 -0.3889649 ]
 [-0.52517084 -0.55450708 -0.44167477  0.51435959  0.45297544]
 [-0.46249647 -0.4883317  -0.3889649   0.45297544  0.39891694]]
